name: Update Plugin Data
on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Nix cache
        uses: DeterminateSystems/flakehub-cache-action@v1

      - name: Restore database cache
        uses: actions/cache/restore@v4
        with:
          path: indexer.db
          key: indexer-db
          restore-keys: |
            indexer-db

      - name: Clear data directory
        run: |
          rm -rf data/
          mkdir -p data/

      - name: Build indexer
        run: nix build .#jb-repo-indexer

      - name: Run indexer
        id: run-indexer
        timeout-minutes: 345
        continue-on-error: true  # Continue even if the indexer fails or times out
        env:
          JB_REPO_INDEXER_LOG: info
        run: |
          ulimit -n 65536
          nix run .#jb-repo-indexer -- --database indexer.db --output-directory data

      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: indexer-db
          path: indexer.db
          retention-days: 7

      - name: Save database cache
        uses: actions/cache/save@v4
        with:
          path: indexer.db
          key: indexer-db

      - name: Check for changes
        if: steps.run-indexer.outcome == 'success'
        id: git-check
        run: |
          git add data/
          git status --porcelain
          echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changed > 0 && steps.run-indexer.outcome == 'success'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "Update plugin data"
          git push
